export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const TOGGLE_ACTIVATE = 'TOGGLE_ACTIVATE';
export const SET_ACTIVE_TARGET = 'SET_ACTIVE_TARGET';
export const SET_STICKY_SCROLL_HEIGHT = 'SET_STICKY_SCROLL_HEIGHT';

